steps:
# Run test
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'python -m pip install tox && tox'

# Build the image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mlapp:latest', '.']
  timeout: 200s

# Push the image
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/$PROJECT_ID/mlapp:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  id: Bash
  entrypoint: /bin/sh
  args:
  - -c
  - |
    echo "List of files and directories within the current working directory"
    ls -l

# Deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  id: Deploy on GKE
  args:
  - run
  - --filename=k8s/
  - --image=gcr.io/$PROJECT_ID/mlapp:latest
  - --location=us-west1-b
  - --cluster=mlkube